Repository googleapis/python-bigquery-pandas, pull requests merged in 2021-11, with the labels that each got.

#413 feat: `to_gbq` uses Parquet by default, use `api_method="load_csv"` for old behavior
  CONTRIBUTING.rst
  ci/requirements-3.7-0.23.2.conda
  ci/requirements-3.9-NIGHTLY.conda
  docs/install.rst
  noxfile.py
  owlbot.py
  pandas_gbq/exceptions.py
  pandas_gbq/features.py
  pandas_gbq/gbq.py
  pandas_gbq/load.py
  setup.py
  testing/constraints-3.7.txt
  tests/system/test_gbq.py
  tests/system/test_to_gbq.py
  tests/unit/test_gbq.py
  tests/unit/test_load.py
Labels: cla: yes, api: bigquery

#383 docs: clarify `table_schema`
  pandas_gbq/gbq.py
Labels: automerge, cla: yes, api: bigquery

#417 feat: allow Python 3.10
  setup.py
  testing/constraints-3.10.txt
  testing/constraints-3.11.txt
Labels: cla: yes, api: bigquery

#420 test: upload DATE column with various dtypes
  CONTRIBUTING.rst
  noxfile.py
  owlbot.py
  setup.py
  tests/system/test_to_gbq.py
Labels: cla: yes, api: bigquery

#423 fix: `to_gbq` allows strings for DATE and floats for NUMERIC, require pandas 0.24+ and db-dtypes
  .circleci/config.yml
  .coveragerc
  ci/requirements-3.7-0.24.2.conda
  ci/requirements-3.9-NIGHTLY.conda
  noxfile.py
  owlbot.py
  pandas_gbq/load.py
  setup.py
  testing/constraints-3.7.txt
  tests/system/test_gbq.py
  tests/system/test_to_gbq.py
  tests/unit/test_load.py
Labels: do not merge, cla: yes, api: bigquery

#428 test: add session with prerelease dependencies
  .kokoro/continuous/prerelease.cfg
  .kokoro/presubmit/prerelease.cfg
  noxfile.py
  owlbot.py
Labels: cla: yes, api: bigquery
