Repository googleapis/python-bigquery-pandas, pull requests merged in 2024-05, with the labels that each got.

#764 feat: Adds pip freeze to several sessions in the noxfile to aid in troubleshooting
  noxfile.py
Labels: api: bigquery, size: xs

#763 bug: add missing latency check
  noxfile.py
  pandas_gbq/gbq.py
  tests/system/test_gbq.py
Labels: api: bigquery, size: m

#769 feat: `read_gbq` suggests using BigQuery DataFrames with large results
  docs/index.rst
  noxfile.py
  pandas_gbq/constants.py
  pandas_gbq/exceptions.py
  pandas_gbq/features.py
  pandas_gbq/gbq.py
  tests/unit/test_gbq.py
  tests/unit/test_to_gbq.py
Labels: api: bigquery, size: m

#773 docs: use a short-link to BigQuery DataFrames
  docs/index.rst
  pandas_gbq/gbq.py
Labels: api: bigquery, size: xs

#770 chore: sort imports
  docs/conf.py
  docs/intro.rst
  docs/reading.rst
  docs/samples
  docs/writing.rst
  noxfile.py
  owlbot.py
  pandas_gbq/__init__.py
  pandas_gbq/features.py
  pandas_gbq/gbq.py
  pandas_gbq/load.py
  pandas_gbq/query.py
  pandas_gbq/schema.py
  samples/snippets/conftest.py
  samples/snippets/noxfile.py
  samples/snippets/read_gbq_test.py
  samples/snippets/to_gbq_simple.py
  setup.py
  tests/system/conftest.py
  tests/system/test_auth.py
  tests/system/test_gbq.py
  tests/system/test_read_gbq.py
  tests/system/test_read_gbq_with_bqstorage.py
  tests/system/test_to_gbq.py
  tests/unit/test_context.py
  tests/unit/test_gbq.py
  tests/unit/test_load.py
  tests/unit/test_query.py
  tests/unit/test_timestamp.py
  tests/unit/test_to_gbq.py
Labels: automerge, api: bigquery, size: m

#768 fix: handle None when converting numerics to parquet
  pandas_gbq/load.py
  tests/unit/test_load.py
Labels: api: bigquery, size: s

#777 fix: clean up nox sessions to uniformly displays package versions for debug purposes
  noxfile.py
Labels: api: bigquery, size: xs
